version: "3.9"

services:
  flask_app:
    build: .
    ports:
      - "8080:8080"

  mysql:
    image: library/mysql:latest
    container_name: mysql
    volumes:
      - ./dbdata:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 11111
    ports:
      - "8090:8080"